import { Department } from "@/types";

export const initialDepartments: Department[] = [
  {
    id: "dept-1",
    name: "Engineering & Technology",
    code: "ENG",
    description: "Software engineering, infrastructure, DevOps, and platform architecture teams.",
    managerId: "emp-1",
    managerName: "Alexander Wright",
    managerAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    employeeCount: 42,
    budget: 680000,
    status: "active",
    createdAt: "2023-01-15",
  },
  {
    id: "dept-2",
    name: "Product & UI/UX Design",
    code: "PRD",
    description: "Product strategy, user research, wireframing, and design system governance.",
    managerId: "emp-2",
    managerName: "Elena Rostova",
    managerAvatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    employeeCount: 16,
    budget: 240000,
    status: "active",
    createdAt: "2023-02-01",
  },
  {
    id: "dept-3",
    name: "Sales & Enterprise Accounts",
    code: "SLS",
    description: "Global enterprise sales, inbound conversions, and strategic customer growth.",
    managerId: "emp-3",
    managerName: "Marcus Vance",
    managerAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    employeeCount: 28,
    budget: 450000,
    status: "active",
    createdAt: "2023-01-20",
  },
  {
    id: "dept-4",
    name: "People & Human Resources",
    code: "HR",
    description: "Talent acquisition, onboarding, workplace culture, benefits, and compliance.",
    managerId: "emp-4",
    managerName: "Sarah Jenkins",
    managerAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    employeeCount: 9,
    budget: 180000,
    status: "active",
    createdAt: "2023-01-10",
  },
  {
    id: "dept-5",
    name: "Finance & Accounting",
    code: "FIN",
    description: "Corporate financial planning, payroll execution, audit, and tax reporting.",
    managerId: "emp-5",
    managerName: "David Chen",
    managerAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    employeeCount: 12,
    budget: 290000,
    status: "active",
    createdAt: "2023-03-01",
  },
  {
    id: "dept-6",
    name: "Marketing & Growth",
    code: "MKT",
    description: "Brand identity, demand generation, SEO, content creation, and media relations.",
    managerId: "emp-6",
    managerName: "Olivia Taylor",
    managerAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    employeeCount: 18,
    budget: 320000,
    status: "active",
    createdAt: "2023-02-15",
  },
  {
    id: "dept-7",
    name: "Customer Support & Success",
    code: "CSS",
    description: "Client onboarding, Tier 1-3 helpdesk, customer retention, and NPS optimization.",
    managerId: "emp-7",
    managerName: "Julian Ramirez",
    managerAvatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
    employeeCount: 24,
    budget: 260000,
    status: "active",
    createdAt: "2023-04-10",
  },
];
