import { Employee } from "@/types";

export const initialEmployees: Employee[] = [
  {
    id: "emp-1",
    employeeCode: "EMP-1001",
    firstName: "Alexander",
    lastName: "Wright",
    fullName: "Alexander Wright",
    email: "alexander.wright@company.com",
    phone: "+1 (555) 234-5678",
    dateOfBirth: "1988-04-12",
    gender: "male",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    departmentId: "dept-1",
    departmentName: "Engineering & Technology",
    designation: "VP of Engineering",
    joiningDate: "2021-03-15",
    employmentType: "full_time",
    managerName: "Board of Directors",
    status: "active",
    address: "742 Evergreen Terrace",
    city: "San Francisco",
    state: "CA",
    country: "United States",
    postalCode: "94107",
    baseSalary: 185000,
    paymentFrequency: "monthly",
    bankName: "Silicon Valley Bank",
    accountNumber: "**** 4892",
    attendanceRate: 98.4,
    leaveBalance: 18,
    performanceRating: 4.9,
  },
  {
    id: "emp-2",
    employeeCode: "EMP-1002",
    firstName: "Elena",
    lastName: "Rostova",
    fullName: "Elena Rostova",
    email: "elena.rostova@company.com",
    phone: "+1 (555) 345-6789",
    dateOfBirth: "1992-08-23",
    gender: "female",
    avatarUrl: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    departmentId: "dept-2",
    departmentName: "Product & UI/UX Design",
    designation: "Head of Product Design",
    joiningDate: "2021-06-01",
    employmentType: "full_time",
    managerName: "Alexander Wright",
    status: "active",
    address: "128 Market Street, Apt 4B",
    city: "San Francisco",
    state: "CA",
    country: "United States",
    postalCode: "94105",
    baseSalary: 155000,
    paymentFrequency: "monthly",
    bankName: "Chase Bank",
    accountNumber: "**** 9123",
    attendanceRate: 96.2,
    leaveBalance: 14,
    performanceRating: 4.8,
  },
  {
    id: "emp-3",
    employeeCode: "EMP-1003",
    firstName: "Marcus",
    lastName: "Vance",
    fullName: "Marcus Vance",
    email: "marcus.vance@company.com",
    phone: "+1 (555) 456-7890",
    dateOfBirth: "1989-11-05",
    gender: "male",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    departmentId: "dept-3",
    departmentName: "Sales & Enterprise Accounts",
    designation: "Enterprise Sales Director",
    joiningDate: "2022-01-10",
    employmentType: "full_time",
    managerName: "Chief Executive Officer",
    status: "active",
    address: "550 Montgomery St",
    city: "San Francisco",
    state: "CA",
    country: "United States",
    postalCode: "94111",
    baseSalary: 140000,
    paymentFrequency: "monthly",
    bankName: "Bank of America",
    accountNumber: "**** 7731",
    attendanceRate: 94.0,
    leaveBalance: 12,
    performanceRating: 4.7,
  },
  {
    id: "emp-4",
    employeeCode: "EMP-1004",
    firstName: "Sarah",
    lastName: "Jenkins",
    fullName: "Sarah Jenkins",
    email: "sarah.jenkins@company.com",
    phone: "+1 (555) 567-8901",
    dateOfBirth: "1991-02-19",
    gender: "female",
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    departmentId: "dept-4",
    departmentName: "People & Human Resources",
    designation: "Lead HR Business Partner",
    joiningDate: "2021-09-01",
    employmentType: "full_time",
    managerName: "Chief Executive Officer",
    status: "active",
    address: "310 Townsend Street",
    city: "San Francisco",
    state: "CA",
    country: "United States",
    postalCode: "94107",
    baseSalary: 125000,
    paymentFrequency: "monthly",
    bankName: "Wells Fargo",
    accountNumber: "**** 3302",
    attendanceRate: 99.1,
    leaveBalance: 20,
    performanceRating: 4.9,
  },
  {
    id: "emp-5",
    employeeCode: "EMP-1005",
    firstName: "David",
    lastName: "Chen",
    fullName: "David Chen",
    email: "david.chen@company.com",
    phone: "+1 (555) 678-9012",
    dateOfBirth: "1987-07-30",
    gender: "male",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    departmentId: "dept-5",
    departmentName: "Finance & Accounting",
    designation: "Finance Controller",
    joiningDate: "2021-11-15",
    employmentType: "full_time",
    managerName: "Chief Executive Officer",
    status: "active",
    address: "88 Colin P Kelly Jr St",
    city: "San Francisco",
    state: "CA",
    country: "United States",
    postalCode: "94107",
    baseSalary: 138000,
    paymentFrequency: "monthly",
    bankName: "Citi Bank",
    accountNumber: "**** 5518",
    attendanceRate: 97.5,
    leaveBalance: 16,
    performanceRating: 4.6,
  },
  {
    id: "emp-6",
    employeeCode: "EMP-1006",
    firstName: "Olivia",
    lastName: "Taylor",
    fullName: "Olivia Taylor",
    email: "olivia.taylor@company.com",
    phone: "+1 (555) 789-0123",
    dateOfBirth: "1994-05-14",
    gender: "female",
    avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    departmentId: "dept-6",
    departmentName: "Marketing & Growth",
    designation: "Senior Growth Marketing Lead",
    joiningDate: "2022-04-18",
    employmentType: "full_time",
    managerName: "Marcus Vance",
    status: "active",
    address: "220 King Street",
    city: "San Francisco",
    state: "CA",
    country: "United States",
    postalCode: "94107",
    baseSalary: 115000,
    paymentFrequency: "monthly",
    bankName: "Chase Bank",
    accountNumber: "**** 8894",
    attendanceRate: 95.8,
    leaveBalance: 15,
    performanceRating: 4.7,
  },
  {
    id: "emp-7",
    employeeCode: "EMP-1007",
    firstName: "Julian",
    lastName: "Ramirez",
    fullName: "Julian Ramirez",
    email: "julian.ramirez@company.com",
    phone: "+1 (555) 890-1234",
    dateOfBirth: "1993-10-09",
    gender: "male",
    avatarUrl: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
    departmentId: "dept-7",
    departmentName: "Customer Support & Success",
    designation: "Customer Success Team Lead",
    joiningDate: "2022-07-01",
    employmentType: "full_time",
    managerName: "Sarah Jenkins",
    status: "active",
    address: "450 4th Street",
    city: "San Francisco",
    state: "CA",
    country: "United States",
    postalCode: "94107",
    baseSalary: 95000,
    paymentFrequency: "monthly",
    bankName: "Bank of America",
    accountNumber: "**** 1209",
    attendanceRate: 93.4,
    leaveBalance: 11,
    performanceRating: 4.5,
  },
  {
    id: "emp-8",
    employeeCode: "EMP-1008",
    firstName: "Priya",
    lastName: "Patel",
    fullName: "Priya Patel",
    email: "priya.patel@company.com",
    phone: "+1 (555) 901-2345",
    dateOfBirth: "1995-12-03",
    gender: "female",
    avatarUrl: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80",
    departmentId: "dept-1",
    departmentName: "Engineering & Technology",
    designation: "Senior Full Stack Engineer",
    joiningDate: "2022-08-15",
    employmentType: "full_time",
    managerName: "Alexander Wright",
    status: "active",
    address: "101 California St",
    city: "San Francisco",
    state: "CA",
    country: "United States",
    postalCode: "94111",
    baseSalary: 148000,
    paymentFrequency: "monthly",
    bankName: "Wells Fargo",
    accountNumber: "**** 6643",
    attendanceRate: 98.0,
    leaveBalance: 19,
    performanceRating: 4.9,
  },
  {
    id: "emp-9",
    employeeCode: "EMP-1009",
    firstName: "Lucas",
    lastName: "Mendoza",
    fullName: "Lucas Mendoza",
    email: "lucas.mendoza@company.com",
    phone: "+1 (555) 012-3456",
    dateOfBirth: "1996-03-22",
    gender: "male",
    avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80",
    departmentId: "dept-1",
    departmentName: "Engineering & Technology",
    designation: "DevOps & Cloud Architect",
    joiningDate: "2023-02-01",
    employmentType: "full_time",
    managerName: "Alexander Wright",
    status: "active",
    address: "650 Mission St",
    city: "San Francisco",
    state: "CA",
    country: "United States",
    postalCode: "94105",
    baseSalary: 142000,
    paymentFrequency: "monthly",
    bankName: "Chase Bank",
    accountNumber: "**** 2291",
    attendanceRate: 97.2,
    leaveBalance: 17,
    performanceRating: 4.8,
  },
  {
    id: "emp-10",
    employeeCode: "EMP-1010",
    firstName: "Sophie",
    lastName: "Dubois",
    fullName: "Sophie Dubois",
    email: "sophie.dubois@company.com",
    phone: "+1 (555) 123-9876",
    dateOfBirth: "1994-09-17",
    gender: "female",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    departmentId: "dept-2",
    departmentName: "Product & UI/UX Design",
    designation: "Senior UI/UX Designer",
    joiningDate: "2023-04-10",
    employmentType: "full_time",
    managerName: "Elena Rostova",
    status: "on_leave",
    address: "333 Bush Street",
    city: "San Francisco",
    state: "CA",
    country: "United States",
    postalCode: "94104",
    baseSalary: 120000,
    paymentFrequency: "monthly",
    bankName: "Bank of America",
    accountNumber: "**** 8092",
    attendanceRate: 91.5,
    leaveBalance: 8,
    performanceRating: 4.6,
  },
  {
    id: "emp-11",
    employeeCode: "EMP-1011",
    firstName: "Kavita",
    lastName: "Nair",
    fullName: "Kavita Nair",
    email: "kavita.nair@company.com",
    phone: "+1 (555) 234-8765",
    dateOfBirth: "1997-06-11",
    gender: "female",
    avatarUrl: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80",
    departmentId: "dept-3",
    departmentName: "Sales & Enterprise Accounts",
    designation: "Account Executive",
    joiningDate: "2023-07-15",
    employmentType: "full_time",
    managerName: "Marcus Vance",
    status: "probation",
    address: "181 Fremont St",
    city: "San Francisco",
    state: "CA",
    country: "United States",
    postalCode: "94105",
    baseSalary: 85000,
    paymentFrequency: "monthly",
    bankName: "Wells Fargo",
    accountNumber: "**** 4410",
    attendanceRate: 96.0,
    leaveBalance: 12,
    performanceRating: 4.4,
  },
  {
    id: "emp-12",
    employeeCode: "EMP-1012",
    firstName: "Benjamin",
    lastName: "Foster",
    fullName: "Benjamin Foster",
    email: "benjamin.foster@company.com",
    phone: "+1 (555) 345-7654",
    dateOfBirth: "1990-01-28",
    gender: "male",
    avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80",
    departmentId: "dept-4",
    departmentName: "People & Human Resources",
    designation: "Technical Recruiter",
    joiningDate: "2022-10-01",
    employmentType: "contract",
    managerName: "Sarah Jenkins",
    status: "active",
    address: "505 Howard St",
    city: "San Francisco",
    state: "CA",
    country: "United States",
    postalCode: "94105",
    baseSalary: 92000,
    paymentFrequency: "biweekly",
    bankName: "Chase Bank",
    accountNumber: "**** 6128",
    attendanceRate: 95.0,
    leaveBalance: 10,
    performanceRating: 4.5,
  }
];
